name: Templates Deploying For API-Connections 
on: 
 workflow_dispatch:
jobs:
 BlobConnectionDeploying:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    
     - name: Checkout source code 
       uses: actions/checkout@master
   
     - uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     - name: Deploy ARM Template
       uses: azure/arm-deploy@v1
       with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./BlobConnection/blob.json
          parameters: ./BlobConnection/blob-parameters-dev.json
